export const TRADE_OPTIONS = [
  "Builder",
  "Carpenter",
  "Electrician",
  "Plumber",
  "Gas Fitter",
  "Painter",
  "Tiler",
  "Landscaper",
  "Concreter",
  "Roofer",
  "Bricklayer",
  "Plasterer",
  "Gyprocker",
  "Renderer",
  "Flooring Installer",
  "Cabinet Maker",
  "Joiner",
  "Glazier",
  "Fencer",
  "Waterproofer",
  "Air Conditioning / HVAC",
  "Solar Installer",
  "Excavation / Earthworks",
  "Demolition Contractor",
  "Stonemason",
  "Scaffolder",
  "Locksmith",
  "Handyman",
  "Pool Builder / Maintenance",
  "Pest Control",
  "Garage Door Installer",
  "Insulation Installer",
  "Gutter Installer / Maintenance",
  "Arborist / Tree Services",
  "Other",
] as const;